name: Deploy Python WebJob to Azure Web App - test-webjob-appservice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: List repo structure (debug)
        run: ls -R

      - name: Zip WebJob files
        run: |
          cd webjobs
          zip -r ../webjob.zip App_Data
          cd ..
      
      - name: Verify zip file created
        run: ls -lh

      - name: Upload WebJob artifact
        uses: actions/upload-artifact@v4
        with:
          name: webjob-artifact
          path: ./webjob.zip 

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download WebJob artifact
        uses: actions/download-artifact@v4
        with:
          name: webjob-artifact
          path: .

      - name: Debug downloaded files
        run: ls -lh

      - name: Deploy WebJob to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'test-webjob-appservice'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5858E5894C88408DA304B34338E4B805 }}
          package: ./webjob.zip

