# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Deploy Python WebJob using Azure CLI - test-gitapp-funcapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:       
      id-token: write
      contents: read
      
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create clean zip (rooted at App_Data)
        run: |
          cd $GITHUB_WORKSPACE
          zip -r webjob.zip .

      - name: List repo contents
        run: |
          pwd
          ls -R
          
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F1625DACF2EB48919A1FA4E3527D2ABF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FDDBD8E3B5354471871D6C11ABCC2A43 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C925989C39504847B6D6D153507DF7BC }}

      - name: Deploy WebJob with CLI
        run: |
            
            az webapp deploy \
            --resource-group test-VScode-rg \
            --name test-gitapp-funcapp \
            --src-path webjob.zip  \
            --type zip
            


          


































