# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - test-gitapp-funcapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

      - name: Prepare artifact (only App_Data)
        run: |
          mkdir output
          cp -r App_Data output/
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webjob-artifact
          path: output/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webjob-artifact
          path: .

      - name: Create deployment zip
        run: |
          cd output
          zip -r webjob.zip 
          
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F1625DACF2EB48919A1FA4E3527D2ABF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FDDBD8E3B5354471871D6C11ABCC2A43 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C925989C39504847B6D6D153507DF7BC }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'test-gitapp-funcapp'
          slot-name: 'Production'
          package: webjob.zip

          





